
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[462] =
    {   0,
        0,    0,  117,  115,    2,    1,    1,   78,  115,   62,
       88,  103,  115,   63,   64,   86,   89,   69,   90,   71,
       87,  111,  111,   72,   70,   98,   80,  100,   73,   62,
       67,   68,  108,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   65,
      106,   66,   76,   77,    0,    7,    0,   62,   85,  101,
      102,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   81,   74,   83,   75,   84,  114,    0,    3,
       82,  114,  112,    0,    0,  114,    0,  112,    0,    0,
      111,  111,    0,   94,   97,   79,   99,   96,   62,  107,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       21,   62,   62,   62,   62,   62,   62,   62,   62,   30,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,  104,
      105,    0,    0,    0,    8,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  114,  114,    0,
        0,    0,    0,    0,    3,  114,  114,    0,    0,  110,
        0,  114,    0,  109,   91,   93,   95,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   29,   62,   62,   62,

       34,   62,   62,   38,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       54,   62,   62,   62,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  114,
        0,    0,    4,  114,    0,    0,  114,  110,  110,    0,
      114,  114,    0,    0,    0,  109,  109,    0,    0,   92,
       62,   62,   62,   62,   62,   14,   15,   62,   17,   62,
       62,   62,   62,   62,   23,   24,   62,   62,   62,   62,
       58,   62,   62,   62,   62,   36,   62,   61,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   50,

       62,   62,   60,   55,   62,   62,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,  114,    0,  114,    0,
        0,    0,    0,  109,    0,    0,  113,  109,   62,   62,
       62,   62,   13,   16,   18,   59,   62,   62,   62,   62,
       27,   28,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   44,   62,   62,   47,   62,   62,   52,   62,
       62,   57,    0,    0,    0,    0,    0,    0,  109,  113,
      113,    0,   62,   62,   11,   62,   62,   62,   22,   62,
       62,   62,   32,   62,   62,   37,   62,   62,   62,   42,
       43,   45,   62,   48,   62,   51,   62,   62,    0,    0,

       62,   62,   12,   62,   20,   25,   26,   62,   62,   62,
       39,   40,   62,   62,   62,   62,   62,    0,   62,   10,
       19,   62,   62,   62,   62,   46,   62,   62,   56,    0,
       62,   62,   62,   35,   41,   62,   53,    0,   62,   31,
       33,   62,    0,   62,   62,    0,   62,   49,    0,   62,
        0,   62,    0,   62,    6,    6,    0,   62,    5,    5,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   24,   24,   24,   25,   25,   26,   27,   28,
       29,   30,   31,    1,   32,   33,   32,   34,   35,   34,
        9,    9,    9,    9,    9,   36,    9,    9,    9,   37,
        9,    9,   38,    9,    9,    9,    9,   39,    9,    9,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,    9,   54,   55,   56,   57,
       58,   59,    9,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    5,    1,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1,    6,    6,    6,    6,    7,    8,    3,    3,    1,
        1,    1,    1,    9,    6,    6,    6,    6,    6,    6,
        3,    3,    3,    3,    7,    3,    3,    3,    8,    3,
        3,    3,   10,    3,    3,    3,    3,    3,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[486] =
    {   0,
        0,    0, 1057, 1058, 1058, 1058, 1058, 1027,   65,    0,
     1026,   63, 1013,   73, 1058, 1024,   60, 1058,   59,   59,
       70,  116,  164, 1058, 1058,   58, 1023,   64, 1058,  984,
     1058, 1058, 1021,   49,   38,   57,   42,   59,  101,  991,
       47,  990,   68,   73,  998,   80,   70,  988,  993, 1058,
       78, 1058, 1058, 1058,  116, 1058,  212,    0, 1058, 1058,
     1058, 1032,  268,  191,  981,  975,  989,  982,  984,  981,
      979,  984, 1058, 1058, 1058, 1058, 1058,  311,  158,    0,
     1058,  156,  176,  343,  146, 1058,  243, 1058, 1016,  226,
        0, 1058,  260, 1005, 1058, 1058, 1058,  140,  972, 1058,

      971,  970,  972,  980,  966,  113,  982,  981,  968,  974,
      960,  961,  958,  958,  964,  961,  959,  956,  953,    0,
      955,  133,  956,  950,  946,  955,  962,  100,  962,  945,
      948,   84,  946,  951,  946,   48,  158,  163,  949, 1058,
     1058,  278,  299,  938, 1058,  988,  233,  326,  936,  938,
      935,  951,  932,  936,  931,  935,  933,    0, 1058,  358,
      272,  225,  300,  324,    0,  373, 1058,  388,  403,  393,
      348,  409,    0,  419, 1058, 1058,  961,  927,  926,  938,
      931,  940,  935,  934,  935,  921,  919,  140,  934,  932,
      928,  920,  926,  913,  928,  927,    0,  913,  152,  908,

      920,  917,  914,    0,  911,  911,  900,  901,  907,  898,
      900,  897,  905,  908,  886,  898,  883,  882,  880,  887,
        0,  880,  879,  851,  378,  176,    0,  330,  893,    0,
      851,  852,  840,  853,  842,  438,  818,  807,  443,  448,
      436,  472, 1058,    0,  478,  483,  489,  440, 1058,  266,
      494, 1058,  524,  492,  304,  516, 1058,  540,  816, 1058,
      810,  789,  718,  657,  646,    0,    0,  647,    0,  637,
      634,  642,  631,  638,    0,    0,  635,  642,  635,  627,
        0,  639,  626,  640,  624,    0,  608,    0,  624,  622,
      617,  612,  603,  600,  607,  612,  595,  606,  600,    0,

      585,  587,    0,    0,  585,  588,  219,    0,  617,    0,
      571,  572,  564,  440, 1058,  562,  555,  560,  572,  586,
      513,  529,  554,  581,  579,  610,  620,  602,  563,  570,
      552,  567,    0,    0,    0,    0,  545,  546,  543,  542,
      532,    0,  530,  512,  513,  519,  518,  508,  493,  507,
      496,  484,    0,  493,  472,    0,  480,  471,  469,  474,
      473,    0,    0,    0,  474,  475,  612,  614,    0,  653,
     1058,  658,  703,  474,    0,  463,  446,  435,    0,  433,
      426,  442,    0,  443,  444,    0,  439,  437,  423,    0,
        0,    0,  433,    0,  423,    0,  431,  424,  265,  402,

      400,  388,    0,  400,    0,    0,    0,  388,  387,  388,
        0,    0,  371,  359,  359,  348,  354,  327,  326,    0,
        0,  326,  327,  335,  327,    0,  305,  295,    0,  294,
      281,  276,  276,    0,    0,  256,    0,    0,  775,    0,
        0,  268,  254,  253,  263,  248,  238,    0,  226,  225,
      220,  214,  201,  181,  177,  176,  169,  166, 1058,    0,
     1058,  847,  855,  865,  875,  885,  891,  892,  897,  907,
      205,  913,  190,  186,  917,  921,  925,  929,  170,  166,
      933,  937,  121,   72,  946
    } ;

static yyconst flex_int16_t yy_def[486] =
    {   0,
      461,    1,  461,  461,  461,  461,  461,  461,  462,  463,
      461,  461,  464,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  463,
      461,  461,  461,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  461,
      461,  461,  461,  461,  462,  461,  461,  463,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  465,  466,
      461,  461,   22,  461,  461,  461,  461,  461,  467,  461,
       23,  461,  461,  461,  461,  461,  461,  461,  463,  461,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  461,
      461,  462,  462,  468,  461,  461,  461,  461,  469,  461,
      461,  461,  461,  461,  461,  461,  461,   78,  461,  461,
      461,  465,  465,  470,  466,  461,  461,  461,  461,  461,
      461,  461,  471,  472,  461,  461,  461,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  462,  462,  473,  461,  461,  474,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      465,  465,  461,  166,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  475,  476,  477,  461,  461,  478,  461,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  462,  479,  461,  480,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      475,  475,  481,  477,  482,  461,  461,  472,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  483,  484,  461,  461,  481,  481,  324,  461,
      461,  461,  461,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  462,  461,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  461,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  461,
      463,  463,  463,  463,  463,  463,  463,  485,  461,  463,
      463,  463,  461,  463,  463,  461,  463,  463,  461,  463,
      461,  463,  461,  463,  461,  463,  461,  463,  461,  463,
        0,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461
    } ;

static yyconst flex_int16_t yy_nxt[1131] =
    {   0,
        4,    5,    6,    5,    7,    5,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   23,   23,   23,   24,   25,   26,   27,   28,
       29,   10,   10,   10,   10,   10,   10,   30,   10,   31,
        4,   32,   33,   10,   34,   35,   36,   37,   38,   39,
       40,   10,   41,   10,   42,   10,   43,   10,   44,   45,
       46,   47,   10,   48,   49,   10,   10,   10,   50,   51,
       52,   53,   56,   60,   64,   74,   76,   62,   64,   78,
       78,   78,   78,   78,   79,   94,   95,   77,   75,   80,
      110,   61,   97,   98,  101,  103,  120,  104,   81,  111,

      217,  106,  121,  122,  105,   57,  140,  218,  107,  102,
       65,  108,  124,  112,  109,  113,  125,  127,   66,   67,
       68,  136,   69,   56,  114,   70,  399,   71,  212,  137,
      126,  131,  128,   72,   82,  129,   83,   83,   83,   83,
       84,  132,  133,  213,  134,  115,  135,  141,   85,   86,
       87,   88,  207,  116,   89,  117,   57,  208,  118,   90,
      163,   85,  163,   86,   87,   86,  170,  170,  176,  177,
       88,  364,  164,  184,  185,  363,  166,  166,  166,  166,
      166,   89,   82,   56,   91,   91,   91,   91,   91,  167,
      168,  310,   64,  200,  201,  308,   64,   86,   87,   92,

      271,  272,  219,  167,  168,  167,  282,   93,  461,  283,
      254,   86,   87,   86,  461,  222,   57,  223,   92,   55,
      220,  461,  460,   55,  221,  459,   56,  163,   65,  163,
      458,  457,  142,  142,  142,  143,   66,   67,   68,  164,
       69,  461,  456,   70,  145,   71,   83,   83,   83,   83,
       84,   72,   55,  228,  228,  228,  228,   55,  171,   57,
      171,   55,  455,  172,  172,  172,  172,  172,   55,   90,
      454,   55,   56,   55,  144,  146,  453,  452,  451,  146,
       91,   91,   91,   91,   91,   56,  248,  248,  147,  147,
      147,  148,  158,  158,  158,  158,  158,  450,  225,  225,

      225,  225,  163,   93,  163,   57,   56,  449,  146,  250,
      448,  447,  446,  146,  164,  161,  445,  146,   57,  226,
      226,  226,  226,  442,  146,  441,  242,  146,  242,  146,
      149,  158,  158,  158,  158,  158,  440,  145,  164,   57,
      258,  145,  439,  243,  159,  160,  229,  229,  229,  229,
      309,  309,  309,  309,  161,  438,  437,  436,  159,  160,
      159,   82,  258,   84,   84,   84,   84,   84,  172,  172,
      172,  172,  172,  239,  435,  239,   86,   87,  240,  240,
      240,  240,  240,  434,  433,   56,  169,  432,  431,  430,
       86,   87,   86,  244,  244,  244,  244,  244,  307,  307,

      307,  307,  429,  246,  428,  246,  167,  168,  247,  247,
      247,  247,  247,  248,  248,  427,  245,  426,   57,  425,
      167,  168,  167,   84,   84,   84,   84,   84,  249,  251,
      251,  251,  251,  251,  424,  423,  250,  255,  163,  314,
      163,  314,  252,  314,  422,  314,  169,  249,  421,  420,
      164,  315,  253,  315,  257,  258,  252,  419,  252,  418,
      248,  248,  259,  240,  240,  240,  240,  240,  317,  317,
      317,  317,  317,  257,  163,  249,  163,  258,  417,  416,
      415,  159,  414,  250,  413,  412,  164,  411,  410,  409,
      408,  318,  407,  406,  249,  159,  405,  159,  244,  244,

      244,  244,  244,  247,  247,  247,  247,  247,  404,  319,
      319,  319,  319,  319,  251,  251,  251,  251,  251,  403,
      402,  245,  167,  236,  236,  398,  397,  252,  258,  396,
      395,  394,  320,  393,  255,  322,  167,  253,  167,  392,
      391,  252,  390,  252,  251,  251,  251,  251,  251,  258,
      258,  257,  258,  389,  388,  326,  322,  326,  387,  325,
      327,  327,  327,  327,  327,  461,  386,  253,  385,  384,
      257,  258,  322,  383,  258,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  382,  381,  461,  159,  380,
      258,  379,  319,  319,  319,  319,  319,  368,  318,  255,

      378,  377,  159,  318,  159,  167,  319,  319,  319,  319,
      319,  376,  258,  375,  374,  320,  257,  258,  373,  167,
      255,  167,  325,  236,  325,  236,  366,  365,  145,  320,
      327,  327,  327,  327,  327,  257,  362,  257,  258,  258,
      370,  370,  370,  370,  370,  259,  361,  360,  258,  359,
      461,  358,  357,  371,  356,  368,  257,  368,  355,  354,
      258,  353,  352,  372,  351,  350,  349,  371,  348,  371,
      258,  347,  461,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  346,  345,  344,  371,  343,  342,  341,
      303,  340,  339,  338,  337,  336,  372,  335,  334,  333,

      371,  372,  371,  400,  400,  332,  400,  400,  400,  400,
      400,  401,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  401,  401,  401,  401,  401,  400,  400,
      400,  400,  400,  400,  401,  401,  401,  401,  401,  401,
      401,  401,  400,  400,  400,  400,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  400,  400,  400,  400,  443,  443,  331,  443,  443,
      443,  443,  443,  444,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  444,  444,  444,  444,  444,

      443,  443,  443,  443,  443,  443,  444,  444,  444,  444,
      444,  444,  444,  444,  443,  443,  443,  443,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  443,  443,  443,  443,   55,  330,   55,
       55,   55,   55,   55,   55,   55,   55,   58,  329,  259,
       58,   58,   58,   58,   58,   62,  316,   62,  236,   62,
       62,   62,   62,   62,   62,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  165,  313,  165,  165,  165,
      165,  165,  165,  165,  165,  174,  174,  227,  312,  236,

      236,  227,  230,  311,  145,  306,  230,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  256,  256,  256,
      256,  256,  321,  305,  321,  321,  323,  304,  323,  324,
      324,  324,  324,  324,  328,  303,  302,  328,  367,  301,
      367,  367,  369,  300,  299,  369,  443,  298,  443,  443,
      443,  443,  443,  443,  443,  443,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      238,  237,  236,  235,  234,  233,  232,  231,  149,  145,

      144,  224,  216,  215,  214,  211,  210,  209,  206,  205,
      204,  203,  202,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  183,  182,  181,
      180,  179,  178,  175,  173,  157,  156,  155,  154,  153,
      152,  151,  150,  145,  139,  138,  130,  123,  119,  100,
       99,   96,   73,   63,   59,   54,  461,    3,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461
    } ;

static yyconst flex_int16_t yy_chk[1131] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    9,   12,   14,   17,   19,  484,   14,   20,
       20,   20,   20,   20,   21,   26,   26,   19,   17,   21,
       37,   12,   28,   28,   34,   35,   41,   35,   21,   37,

      136,   36,   41,   41,   35,    9,   51,  136,   36,   34,
       14,   36,   43,   38,   36,   38,   43,   44,   14,   14,
       14,   47,   14,   55,   38,   14,  483,   14,  132,   47,
       43,   46,   44,   14,   22,   44,   22,   22,   22,   22,
       22,   46,   46,  132,   46,   39,   46,   51,   22,   22,
       22,   22,  128,   39,   22,   39,   55,  128,   39,   22,
       79,   22,   79,   22,   22,   22,   85,   85,   98,   98,
       22,  480,   79,  106,  106,  479,   82,   82,   82,   82,
       82,   22,   23,  226,   23,   23,   23,   23,   23,   82,
       82,  474,   64,  122,  122,  473,   64,   23,   23,   23,

      188,  188,  137,   82,   82,   82,  199,   23,   83,  199,
      471,   23,   23,   23,   83,  138,  226,  138,   23,   57,
      137,   83,  458,   57,  137,  457,  307,  162,   64,  162,
      456,  455,   57,   57,   57,   57,   64,   64,   64,  162,
       64,   83,  454,   64,  147,   64,   90,   90,   90,   90,
       90,   64,   57,  147,  147,  147,  147,   57,   87,  307,
       87,   57,  453,   87,   87,   87,   87,   87,   57,   90,
      452,   57,  399,   57,   57,   63,  451,  450,  449,   63,
       93,   93,   93,   93,   93,  142,  250,  250,   63,   63,
       63,   63,  161,  161,  161,  161,  161,  447,  142,  142,

      142,  142,  163,   93,  163,  399,  143,  446,   63,  250,
      445,  444,  443,   63,  163,  161,  442,   63,  142,  143,
      143,  143,  143,  436,   63,  433,  164,   63,  164,   63,
       63,   78,   78,   78,   78,   78,  432,  148,  164,  143,
      255,  228,  431,  164,   78,   78,  148,  148,  148,  148,
      228,  228,  228,  228,   78,  430,  428,  427,   78,   78,
       78,   84,  255,   84,   84,   84,   84,   84,  171,  171,
      171,  171,  171,  160,  425,  160,   84,   84,  160,  160,
      160,  160,  160,  424,  423,  225,   84,  422,  419,  418,
       84,   84,   84,  166,  166,  166,  166,  166,  225,  225,

      225,  225,  417,  168,  416,  168,  166,  166,  168,  168,
      168,  168,  168,  170,  170,  415,  166,  414,  225,  413,
      166,  166,  166,  169,  169,  169,  169,  169,  170,  172,
      172,  172,  172,  172,  410,  409,  170,  174,  241,  236,
      241,  314,  172,  236,  408,  314,  169,  170,  404,  402,
      241,  236,  172,  314,  174,  174,  172,  401,  172,  400,
      248,  248,  174,  239,  239,  239,  239,  239,  240,  240,
      240,  240,  240,  174,  242,  248,  242,  174,  398,  397,
      395,  240,  393,  248,  389,  388,  242,  387,  385,  384,
      382,  240,  381,  380,  248,  240,  378,  240,  245,  245,

      245,  245,  245,  246,  246,  246,  246,  246,  377,  247,
      247,  247,  247,  247,  251,  251,  251,  251,  251,  376,
      374,  245,  247,  366,  365,  361,  360,  251,  254,  359,
      358,  357,  247,  355,  256,  254,  247,  251,  247,  354,
      352,  251,  351,  251,  253,  253,  253,  253,  253,  321,
      254,  256,  256,  350,  349,  258,  321,  258,  348,  256,
      258,  258,  258,  258,  258,  322,  347,  253,  346,  345,
      256,  321,  322,  344,  256,  317,  317,  317,  317,  317,
      318,  318,  318,  318,  318,  343,  341,  322,  317,  340,
      323,  339,  319,  319,  319,  319,  319,  323,  317,  324,

      338,  337,  317,  318,  317,  319,  320,  320,  320,  320,
      320,  332,  323,  331,  330,  319,  324,  324,  329,  319,
      328,  319,  325,  316,  324,  313,  312,  311,  309,  320,
      326,  326,  326,  326,  326,  324,  306,  328,  328,  324,
      327,  327,  327,  327,  327,  328,  305,  302,  367,  301,
      368,  299,  298,  327,  297,  367,  328,  368,  296,  295,
      328,  294,  293,  327,  292,  291,  290,  327,  289,  327,
      367,  287,  368,  370,  370,  370,  370,  370,  372,  372,
      372,  372,  372,  285,  284,  283,  370,  282,  280,  279,
      278,  277,  274,  273,  272,  271,  370,  270,  268,  265,

      370,  372,  370,  373,  373,  264,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  439,  439,  263,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  462,  262,  462,
      462,  462,  462,  462,  462,  462,  462,  463,  261,  259,
      463,  463,  463,  463,  463,  464,  238,  464,  237,  464,
      464,  464,  464,  464,  464,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  466,  235,  466,  466,  466,
      466,  466,  466,  466,  466,  467,  467,  468,  234,  233,

      232,  468,  469,  231,  229,  224,  469,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  472,  472,  472,
      472,  472,  475,  223,  475,  475,  476,  222,  476,  477,
      477,  477,  477,  477,  478,  220,  219,  478,  481,  218,
      481,  481,  482,  217,  216,  482,  485,  215,  485,  485,
      485,  485,  485,  485,  485,  485,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  203,  202,  201,  200,
      198,  196,  195,  194,  193,  192,  191,  190,  189,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  146,

      144,  139,  135,  134,  133,  131,  130,  129,  127,  126,
      125,  124,  123,  121,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  105,  104,  103,
      102,  101,   99,   94,   89,   72,   71,   70,   69,   68,
       67,   66,   65,   62,   49,   48,   45,   42,   40,   33,
       30,   27,   16,   13,   11,    8,    3,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[117] =
    {   0,
1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include<stdio.h>
#include<string.h>
#include "parser.hpp"

#define DEBUG_MODE 0
#define LEXEME_LENGTH 4096
#define TABLE_LENGTH 4096

#define KEYWORD	0
#define IDENT 1
#define LITERAL 2

char lexeme[LEXEME_LENGTH];
int line=1,col=1;
int lexeme_count=0,error_counter=0;

struct table
{
	char *lexeme;
	int token;
	int line;
}symbol_table[TABLE_LENGTH],error_dump[TABLE_LENGTH];

int find(char *);
void insert(char *,int);
void insert_error(char *);

#line 916 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "lexer.l"


#line 1106 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 462 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1058 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 64 "lexer.l"
{	line++;col=1;if(DEBUG_MODE) printf("\n-----Lexical analyser on line %d------\n\n",line);
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "lexer.l"
col+=strlen(yytext);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 68 "lexer.l"
{	if(DEBUG_MODE)  printf("comment %s on line %d\n",yytext,line);col=1;
			}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 70 "lexer.l"
{	if(DEBUG_MODE) printf("multi line comment %s\n",yytext);
				strcpy(lexeme,yytext);
				int i;
                                for(i=0;i<strlen(lexeme);i++)
                                {
                                        if(lexeme[i]=='\n' || lexeme[i]=='\r') line++;
                                }col=1;
                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "lexer.l"
{	if(DEBUG_MODE)	printf("print statement %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return PRINTL;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "lexer.l"
{	if(DEBUG_MODE)	printf("print statement %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return PRINT;
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "lexer.l"
{	if(DEBUG_MODE)	printf("string %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return STRING;
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 84 "lexer.l"
{	if(DEBUG_MODE)	printf("character %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return CHARACTERS;
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "lexer.l"
{	if(DEBUG_MODE)	printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return CAST;
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 88 "lexer.l"
{	if(DEBUG_MODE)	printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return ABSTRACT;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return ASSERT;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return BOOLEAN;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return BREAK;
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return BYTE;
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 103 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);	return CASE;
			}	
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 106 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return CATCH;
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 109 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return CHAR;
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 112 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return CLASS;
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return CONTINUE;
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 118 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return DEFAULT;
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 121 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return DO;
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return DOUBLE;
			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 127 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme))	insert(lexeme,KEYWORD);return ELSE;
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 130 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return ENUM;
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 133 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return EXTENDS;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 136 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return FINALLY;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 139 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return FINAL;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 142 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return FLOAT;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 145 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return FOR;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return IF;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 151 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return IMPLEMENTS;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 154 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return IMPORT;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 157 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return INSTANCEOF;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 160 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return INT;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 163 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);	
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return INTERFACE;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 166 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return LONG;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 169 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return NATIVE;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 172 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return NEW;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 175 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return PACKAGE;
			}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 178 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return PRIVATE;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 181 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
         			strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return PROTECTED;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 184 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return PUBLIC;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 187 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return RETURN;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 190 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return SHORT;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 193 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return STATIC;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 196 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return STRICTFP;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 199 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return SUPER;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 202 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return SWITCH;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 205 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return SYNCHRONIZED;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 208 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return THIS;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 211 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return THROWS;
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 214 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return THROW;
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 217 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return TRANSIENT;
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 220 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return TRY;
                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 223 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return VOID;
                        }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 226 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return VOLATILE;
                        }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 229 "lexer.l"
{	if(DEBUG_MODE)  printf("keyword %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return WHILE;
                        }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 232 "lexer.l"
{	if(DEBUG_MODE)  printf("reserved word %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return GOTO;
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 235 "lexer.l"
{	if(DEBUG_MODE)  printf("reserved word %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
                                strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,KEYWORD);return CONST;
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 238 "lexer.l"
{	if(DEBUG_MODE)  printf("literal %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,LITERAL);return BOOL;
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 241 "lexer.l"
{	if(DEBUG_MODE)  printf("literal %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme)) insert(lexeme,LITERAL);return  NULLER;
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 244 "lexer.l"
{	if(DEBUG_MODE)  printf("identifier %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				strcpy(lexeme,yytext);if(!find(lexeme))	insert(lexeme,IDENT);return IDENTIFIER;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 247 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LRBRACE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 248 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return RRBRACE;
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 250 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LCBRACE;
			} 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 252 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return RCBRACE;
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 254 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LSBRACE;
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 256 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return RSBRACE;
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 258 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return COMMA;
			}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 260 "lexer.l"
{	if(DEBUG_MODE)  printf("separator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return SEMICOLON;
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 262 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return DOT;
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 264 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return COLON;
			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 266 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return TERNARY;
			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 268 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return INCREMENT;
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 270 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return DECREMENT;
			}    
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 272 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return UNOT;
			}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 274 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return NEQ;
			}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 276 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return NOT;
			}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 278 "lexer.l"
{       if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return COMPARE;
			}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 280 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return EQUAL;
			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 282 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return MULTEQUAL;
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 284 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return DIVEQUAL;
			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 286 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return PLUSEQUAL;
			}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 288 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return MINUSEQUAL;
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 290 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return MODEQUAL;
			}				
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 292 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return MULT;
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 294 "lexer.l"
{       if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return DIV;
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 296 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return MOD;
			}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 298 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return PLUS;
			}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 300 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return MINUS;
			}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 302 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LEFTSHIFTEQUAL;
			}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 304 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return URIGHTSHIFTEQUAL;
			}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 306 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return RIGHTSHIFTEQUAL;
			}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 308 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LEFTSHIFT;
			}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 310 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return URIGHTSHIFT;
			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 312 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return RIGHTSHIFT;
			}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 314 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LEQ;
			}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 316 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return LT;
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 318 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return GEQ;
			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 320 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return GT;
			}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 322 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return AND;
			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 324 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return ANDEQUAL;
			}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 326 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return BAND;
			}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 328 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return OREQUAL;
			}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 330 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return OR;
			}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 332 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return BOR;
			}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 334 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return XOREQUAL;
			}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 336 "lexer.l"
{	if(DEBUG_MODE)  printf("operator %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return XOR;
			}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 338 "lexer.l"
{	if(DEBUG_MODE)  printf("hexadecimal number %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				return HEX_INT;
			}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 341 "lexer.l"
{	if(DEBUG_MODE)  printf("binary number %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				return BIN_INT;
			}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 344 "lexer.l"
{	if(DEBUG_MODE)  printf("number %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return INTEGER;
			}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 346 "lexer.l"
{	if(DEBUG_MODE)  printf("octal number %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				return OCT_INT;
			}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 349 "lexer.l"
{	if(DEBUG_MODE)  printf("hexadecimal float %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				return HEX_FLOAT;
			}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 352 "lexer.l"
{	if(DEBUG_MODE)  printf("float %s on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);return FLOATING;
                        }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 354 "lexer.l"
{	if(DEBUG_MODE)	printf("%s is erraneous on line %d,column %d\n",yytext,line,col);col+=strlen(yytext);
				insert_error(yytext);return ERROR;
			}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 357 "lexer.l"
ECHO;
	YY_BREAK
#line 1958 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 462 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 462 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 461);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 357 "lexer.l"



int find(char *lexeme)
{
	int i,flag=0;
	for(i=0;i<lexeme_count;i++)
	{
		if(strcmp(symbol_table[i].lexeme,lexeme)==0)
			return 1;
	}
	return 0;
}

void insert(char *lexeme,int type)
{
	symbol_table[lexeme_count].lexeme=(char *)malloc(strlen(lexeme)+1);
	strcpy(symbol_table[lexeme_count].lexeme,lexeme);
	symbol_table[lexeme_count].token=type;
	symbol_table[lexeme_count++].line=line;
}

void insert_error(char *error)
{
	error_dump[error_counter].lexeme=(char *)malloc(strlen(error)+1);
        strcpy(error_dump[error_counter].lexeme,error);
        error_dump[error_counter].token=-1;
        error_dump[error_counter++].line=line;
}
/*int main()
{
	yylex();
	printf("\n-----Printing the contents of the symbol table-----\n\n");
	int i;
	for(i=0;i<lexeme_count;i++)
		printf("lexeme %s of type %d was found at line %d\n",symbol_table[i].lexeme,symbol_table[i].token,symbol_table[i].line);
	printf("\n-----Printing the contents of the error dump-------\n\n");
	for(i=0;i<error_counter;i++)
		printf("Error %s was found at line %d\n",error_dump[i].lexeme,error_dump[i].line);	
	return 0;
}*/

